plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm' version '2.2.20'
    id "signing"
    id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
}

ext {
    forge_server_version = '24.0.1'
}

group 'com.bolyartech.forge.server'
version forge_server_version

apply plugin: 'maven-publish'

repositories {
    mavenCentral()
}

dependencies {
    api 'jakarta.servlet:jakarta.servlet-api:5.0.0'
    api 'javax.inject:javax.inject:1'
    api "com.zaxxer:HikariCP:5.0.1"
    implementation 'org.slf4j:slf4j-api:2.0.5'
    implementation 'ch.qos.logback:logback-classic:1.5.32'
    implementation "com.google.guava:guava:33.0.0-jre"
    implementation "commons-cli:commons-cli:1.4"
    api "org.apache.velocity:velocity-engine-core:2.4.1"
    api "org.apache.velocity.tools:velocity-tools-generic:3.1"

    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

test {
    useJUnitPlatform()
}


tasks.withType(Javadoc).configureEach {
    enabled = false
}

tasks.register('javadocJar', Jar) {
    archiveClassifier = 'javadoc'
    from javadoc
}

tasks.register('sourcesJar', Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives javadocJar, sourcesJar
}


javadoc.options.addStringOption('Xdoclint:none', '-quiet')

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId 'com.bolyartech.forge.server'
            artifactId 'forge-server'
            version forge_server_version
            artifact sourcesJar
            artifact javadocJar
            pom {
                name = 'Forge Server'
                artifactId = 'forge-server'
                packaging = 'jar'
                description = 'Forge server is the base for the server part of the Forge framework'
                url = 'https://github.com/ogrebgr/forge-server'

                scm {
                    connection = 'scm:git:https://github.com/ogrebgr/forge-server.git'
                    developerConnection = 'scm:git:https://github.com/ogrebgr/forge-server.git'
                    url = 'https://github.com/ogrebgr/forge-server'
                }

                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }

                developers {
                    developer {
                        id = 'ogremir'
                        name = 'Ognyan Bankov'
                        email = 'bankov@bolyartech.com'
                    }
                }
            }
        }
    }
}

nexusPublishing {
    repositories {
        sonatype {
            stagingProfileId.set("com.bolyartech")
            nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
            snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))
            username = findProperty('ossrhUsername')
            password = findProperty('ossrhPassword')
        }
    }
}


signing {
    sign publishing.publications.mavenJava
}


kotlin {
    jvmToolchain(17)
}

